sparcs-kaist/kono

- kono-fakeserver/.gitignore
- kono-fakeserver/README.md
- kono-fakeserver/package-lock.json
- kono-fakeserver/package.json
- kono-fakeserver/src/server.js
This fake server serves as a test case for the back-end server,
which determines if the rooms are empty based on the signal output from the sensor.
The fake server simulates the movement of virtual customer,
and produces according sensor outputs.
The fake server interacts with the clients using HTTP.
> implemented fake server

- kono-auth/package-lock.json
- kono-auth/package.json
- kono-auth/src/api/v1/auth/auth.control.js
- kono-auth/src/db/models/admin.js
- kono-auth/src/index.js
- kono-auth/src/lib/JWTMiddleware.js
- kono-auth/webpack.config.js
Updates:
- Now uses `@babel/core^7.6.0` since we use spreading feature of ES6
- Now distinguishes development and production environment using `NODE_ENV`
- Now detects (which is done in `JWTMiddleware.js`:
- Rejects JWT if the token is expired
- Reassigns JWT if the token is close to expiring (10 min to expire)
> Fixed issue3

- kono-api/src/api/v1/post/post.control.js
- kono-api/src/api/v1/post/post.test.js
- kono-api/src/db/lib/model.js
- kono-api/src/db/models/image.js
- kono-api/src/db/models/post.js
DB Table을 좀 더 잘 정의하고 중복되는 코드를 줄이기 위한 노력.
(ORM은 마음에 안 들기 때문에 직접 구현!)
> rewrite db models and queries in kono-api (fix #33)

- kono-api/src/api/v1/index.js
- kono-api/src/api/v1/room/index.js
- kono-api/src/api/v1/room/room.control.js
- kono-api/src/api/v1/room/room.test.js
- kono-api/src/db/models/room.js
- kono-api/src/test/test.js
[issue 18](https://github.com/sparcs-kaist/kono/issues/18)
- This pull request contains implementation of only `/recent/:room_number` api without much consideration of scaling of functions to more general purposes.
- Current `room.test.js` doesn't contain logic testing (Testing that involves insertion).
> Added room api

- kono-front/src/api/image.js
- kono-front/src/api/post.js
- kono-front/src/components/ErrorHandlingPanel.js
- kono-front/src/components/Footer.js
- kono-front/src/components/ImageGridPanel.js
- kono-front/src/components/ImageThumbnailPanel.js
- kono-front/src/components/LoginPage.js
- kono-front/src/components/LostFoundPanel.js
- kono-front/src/components/NoticePanel.js
- kono-front/src/components/PostHeader.js
- kono-front/src/components/PostPage.js
- kono-front/src/components/PostPageView.js
- kono-front/src/components/Spinner.js
- kono-front/src/components/StaticContent.js
- kono-front/src/lib/hooks/useFetch.js
- kono-front/src/res/texts/ErrorHandlingPanel.text.json
- kono-front/src/res/texts/NoticePanel.text.json
- kono-front/src/styles/ErrorHandlingPanel.module.scss
- kono-front/src/styles/ImageThumbnailPanel.module.scss
- kono-front/src/styles/RoomPanel.module.scss
- kono-front/src/styles/Spinner.module.scss
API 호출하여 view에 반영 및 error handling 구현 완료.
> kono-front Post, Image API 적용 (fix #21)

- kono-front/src/components/CreditPage.js
- kono-front/src/styles/CreditPage.module.scss
> kono-front (fix #19)

- kono-api/src/api/v1/image/image.control.js
- kono-api/src/api/v1/post/post.control.js
> Kono api issue66

- kono-api/package.json
- kono-api/src/api/v1/index.js
- kono-api/src/api/v1/noti/index.js
- kono-api/src/api/v1/noti/noti.control.js
- kono-api/src/api/v1/noti/noti.test.js
- kono-api/src/lib/token.js
- kono-api/src/test/common.js
- kono-api/src/test/test.js
> Kono api issue51

- kono-api/src/api/v1/noti/noti.test.js
- kono-api/src/api/v1/room/index.js
- kono-api/src/api/v1/room/room.control.js
- kono-api/src/api/v1/room/room.test.js
> Kono api issue74

- kono-front/src/components/App.js
- kono-front/src/components/Footer.js
- kono-front/src/components/Header.js
- kono-front/src/components/HeaderDesktop.js
- kono-front/src/components/HeaderMobile.js
- kono-front/src/res/texts/Header.text.json
- kono-front/src/styles/App.module.scss
- kono-front/src/styles/Footer.module.scss
- kono-front/src/styles/HeaderDesktop.module.scss
- kono-front/src/styles/HeaderMobile.module.scss
- kono-front/src/styles/main.scss
- kono-front/src/styles/mixins/_color.scss
- kono-front/src/styles/mixins/_link.scss
> Kono front issue80

- kono-front/src/components/App.js
- kono-front/src/components/CreditPage.js
- kono-front/src/components/HeaderMobile.js
- kono-front/src/components/LoginPage.js
- kono-front/src/store/modules/config.js
- kono-front/src/store/modules/layout.js
- kono-front/src/styles/App.module.scss
- kono-front/src/styles/Footer.module.scss
- kono-front/src/styles/HeaderMobile.module.scss
- kono-front/src/styles/main.scss
> Kono front issue86

- kono-front/src/styles/CreditPage.module.scss
- kono-front/src/styles/mixins/_all.scss
- kono-front/src/styles/mixins/_responsive.scss
fix #87 
- `@include wide-screen` !!!
> implement wide-screen mixin and responsive CreditPage

- kono-front/src/components/page/LoginPage.js
- kono-front/src/components/page/LoginPageDesktop.js
- kono-front/src/components/page/LoginPageMobile.js
- kono-front/src/styles/LoginPageDesktop.module.scss
- kono-front/src/styles/LoginPageMobile.module.scss
> Kono front issue88

- kono-front/src/components/page/CreditPage.js
- kono-front/src/styles/Footer.module.scss
- kono-front/src/styles/mixins/_responsive.scss
> minor changes

- kono-front/src/components/landing/LostFoundPanel.js
- kono-front/src/components/landing/NoticePanel.js
- kono-front/src/components/page/LandingPage.js
- kono-front/src/styles/ImageThumbnailPanel.module.scss
- kono-front/src/styles/LandingPage.module.scss
- kono-front/src/styles/LostFoundPanel.module.scss
- kono-front/src/styles/NoticePanel.module.scss
- kono-front/src/styles/PanelFooter.module.scss
- kono-front/src/styles/PanelHeader.module.scss
- kono-front/src/styles/RoomPanel.module.scss
- kono-front/src/styles/mixins/_responsive.scss
> Kono front issue79

- kono-api/src/api/v1/image/image.control.js
- kono-api/src/api/v1/post/post.control.js
- kono-api/src/api/v1/post/post.test.js
> add thumbnail to response in GET /api/v1/post

- kono-front/src/styles/LandingPage.module.scss
> add padding to landingpage components

- kono-front/src/components/common/GridPanel.js
- kono-front/src/components/landing/LostFoundPanelMobile.js
- kono-front/src/components/landing/NoticePanelMobile.js
- kono-front/src/styles/LostFoundPanelMobile.module.scss
- kono-front/src/styles/NoticePanelMobile.module.scss
> implement visible scroll menu

- kono-api/src/api/v1/noti/noti.control.js
> update DELETE /api/v1/noti/:sid to soft delete

- kono-arduino/.gitignore
- kono-arduino/kono-arduino.ino
> Kono arduino issue121

- kono-arduino/StreamingQueue.cpp
- kono-arduino/StreamingQueue.h
- kono-arduino/kono-arduino.ino
- kono-arduino/libraries/WebSockets/src/WebSocketsClient.cpp
- kono-judge/judge.py
> Kono arduino issue127

- kono-arduino/StreamingQueue.cpp
- kono-arduino/kono-arduino.ino
> Kono arduino issue123

- kono-arduino/StreamingQueue.cpp
- kono-arduino/kono-arduino.ino
- kono-arduino/libraries/Grove_Human_Presence_Sensor/Grove_Human_Presence_Sensor.cpp
- kono-arduino/libraries/Grove_Human_Presence_Sensor/Grove_Human_Presence_Sensor.h
- kono-judge/judge.py
> Kono arduino issue122

- kono-arduino/StreamingQueue.cpp
- kono-arduino/kono-arduino.ino
- kono-judge/judge.py
> Kono judge issue120

- kono-arduino/StreamingQueue.h
- kono-arduino/kono-arduino.ino
- kono-judge/judge.py
> Kono judge issue131

- kono-judge/.gitignore
- kono-judge/src/client.py
- kono-judge/src/judge.py
> Kono judge issue143

- kono-arduino/kono-arduino.ino
> update data fetch rate

- kono-judge/src/client.py
- kono-judge/src/judge.py
> fix arduino device_id check logic

- kono-judge/Dockerfile
- src/deploy.sh
- src/stage.sh
> fix nodemon command to watch .py files

- kono-arduino/kono-arduino.ino
- kono-judge/src/client.py
> fix problem on using WebSocketClient.begin()

- kono-judge/requirements.txt
- kono-judge/src/judge.py
- kono-judge/src/router.py
> Kono judge issue157

- kono-judge-status/package-lock.json
- kono-judge-status/package.json
- kono-judge-status/src/components/data/DataPanel.js
- kono-judge-status/src/components/provider/DataProvider.js
- kono-judge-status/src/components/visualization/index.js
- kono-judge-status/src/lib/DataManaging.js
- kono-judge-status/src/styles/components/DataPanel.module.scss
> Feature/kono judge status/issue141

- kono-judge-status/src/components/common/Hover.js
- kono-judge-status/src/components/data/DownloadDetailPanel.js
- kono-judge-status/src/components/data/DownloadPanel.js
- kono-judge-status/src/components/page/LandingPage.js
- kono-judge-status/src/lib/DataManaging.js
- kono-judge-status/src/lib/csv.js
- kono-judge-status/src/styles/components/DownloadDetailPanel.module.scss
- kono-judge-status/src/styles/components/DownloadPanel.module.scss
- kono-judge-status/src/styles/components/Hover.module.scss
- kono-judge-status/src/styles/components/LandingPage.module.scss
> Feature/kono judge status/issue168

- kono-judge-status/src/components/data/DataPanel.js
- kono-judge-status/src/lib/DataManaging.js
> implement sampling data for large timescale

- kono-api/src/api/v1/noti/noti.control.js
fix #179 
error일땐 제발 return하는 것 잊지 말자...
> fix bug on noti APIs
